#!/bin/bash

D=`date -u +'Superhemlig nyckel%Y-%m-%d %H:%M'`
echo $D
APPKEY=`echo -n $D|sha256sum|cut -d ' ' -f 1`
echo $APPKEY

#127.0.0.1
#verdandi.silva.se

PORT=5050

echo "Test order 1"
curl -H "Content-type: application/json" -X POST http://localhost:$PORT/inventory -d '{"appkey":"'${APPKEY}'","articles":[{"ItemId":"21120","Quantity":1.0}]}' -i
 
echo "Test order 2"
curl -H "Content-type: application/json" -X POST http://verdandi.silva.se:$PORT/place_order -d '{"appkey": "'${APPKEY}'", "order": {"head":{"OrderIdWeb": 120},"rows":[{"RowIdWeb": 57, "ItemId": "21120", "Quantity": 1.0}]}}' -i

echo "Test order 3"
curl -H "Content-type: application/json" -X POST http://verdandi.silva.se:$PORT/order_info -d '{"appkey": "'${APPKEY}'", "order": {"OrderIdWeb": "120"}}' -i

echo $APPKEY
