#!/bin/sh
# Start/stop the silva rest server test daemon.
#
### BEGIN INIT INFO
# Provides:          silva-restserver-test
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Test Rest server for Silva
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="silva test rest server daemon"
NAME=silva-restserver-test
DAEMON=/usr/share/silva-restserver/rest-server-test
EXTRA_OPTS=--test
PIDFILE=/var/run/rest-server-test.pid
SCRIPTNAME=/etc/init.d/"$NAME"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

#[ -r /etc/default/cron ] && . /etc/default/cron

# We read /etc/environment, but warn about locale information in
# there because it should be in /etc/default/locale.
parse_environment () 
{
    for ENV_FILE in /etc/environment /etc/default/locale; do
        [ -r "$ENV_FILE" ] || continue
        [ -s "$ENV_FILE" ] || continue

         for var in LANG LANGUAGE LC_ALL LC_CTYPE; do
             value=`egrep "^${var}=" "$ENV_FILE" | tail -n1 | cut -d= -f2`
             [ -n "$value" ] && eval export $var=$value

             if [ -n "$value" ] && [ "$ENV_FILE" = /etc/environment ]; then
                 log_warning_msg "/etc/environment has been deprecated for locale information; use /etc/default/locale for $var=$value instead"
             fi
         done
     done

# Get the timezone set.
    if [ -z "$TZ" -a -e /etc/timezone ]; then
        TZ=`cat /etc/timezone` 
    fi
}

# Parse the system's environment
if [ "$READ_ENV" = "yes" ] ; then
    parse_environment
fi


case "$1" in
start)	log_daemon_msg "Starting periodic command scheduler" "silva-restserver test"
        start_daemon -p $PIDFILE $DAEMON $EXTRA_OPTS &
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping periodic command scheduler" "silva-restserver test"
        killproc -p $PIDFILE $DAEMON
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting periodic command scheduler" "silva-restserver test" 
        $0 stop
        $0 start
        ;;
reload|force-reload) log_daemon_msg "Reloading configuration files for periodic command scheduler" "silva-restserver test"
        log_end_msg 0
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)	log_action_msg "Usage: /etc/init.d/silva-restserver-test {start|stop|status|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0
